#include "cut_cell_clay.hpp"
#include "tmesh.cpp"

GEN_MESH(sCUT_CELL_CLAY_STORAGE_POLICY, tMESH_OBJECT_FACTORY,
	 tCUT_CELL_CLAY_VERTEX, tHALF_EDGE, tCUT_CELL_CLAY_FACET);

GEN_MESH_QUERIES(cCUT_CELL_CLAY);

GEN_MESH_CLIPPER(cCUT_CELL_CLAY);

GEN_MESH_FACETS_OPS(cCUT_CELL_CLAY);
